### PR TITLE
Color Lists for looping

### PR DESCRIPTION
**Pull request by paynoattn**
I wrote color lists so that you can easily loop through all the colors if you need all the shades/colors available.

I still need to enable this in LESS and Stylus but as I'm less familiar with these languages someone else might want to?

### CODE REVIEW

**Comment by mrmlnc** [comment]
Okay, this is a better idea of the proposed @AliAmini (sorry, but this color library).However, here is the problem: twice declared colors. But I decide after taking PR.

**Comment by mrmlnc** [comment]
Great, @paynoattn! I created a branch 2.2.0 and added your changes as an mixins for all languages (Less, Scss, Stylus). I introduced you to the [README](https://github.com/mrmlnc/material-color/tree/2.2.0#thanks) file. Thanks for your work!

---

You are not against this situation? :)

**Comment by paynoattn** [comment]
No, and I like the cool new mixin. My only suggestion would be to change your readme from "Looping" to "Mixin." Since your mixin will now do the looping it might be a little confusing.

**Comment by mrmlnc** [comment]
Nice job!

**Pull request closed without merging**
