### PR TITLE
Simply list of base colors

### PR DESCRIPTION
**Pull request by AlexanderKozhevin**
I think this is a good thing. I needed to use such a list in my project.

### CODE REVIEW

**Comment by mrmlnc** [comment]
Thanks for PR. But could you give some explanation? Why need this list in the library?

**Comment by AlexanderKozhevin** [comment]
It's like a basic color palette. And for some cases it's easy to have full list of it. Especially if you want to make pure material style. 
As for me, I did a custom styles for chart library  and I needed to use this basic colors variables, basic ones. And it's definitely not comfortable to scroll though the long file.

**Comment by mrmlnc** [comment]
Hmm, sounds pretty good. Fix the comments and I'll take this PR.

**Comment by AlexanderKozhevin** [comment]
Are you talking about title?
```sass
//
// List of base colors
//
```
Change to this?
```sass
//
// List of base colors
```

**Comment by mrmlnc** [comment]
Lines 13 - 15 in [Less version](https://github.com/AlexanderKozhevin/material-color/blob/master/material-color.less#L13-L15) and [Stylus version](https://github.com/AlexanderKozhevin/material-color/blob/292034f5b6ece765893766942404e10a266a3fbf/material-color.styl#L13-L15).
image

**Comment by AlexanderKozhevin** [comment]
Fixed it)

**Comment by mrmlnc** [comment]
Thanks for work :muscle:

**Pull request merged**
